// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_Gibbs_Prob_Results_BetaH
List rcpp_Gibbs_Prob_Results_BetaH(NumericVector x_vec, NumericVector n_vec, NumericVector a_vec, NumericVector CDF_value, NumericVector theta, IntegerVector n_gibbs, IntegerVector n_gibbs_burnin, IntegerVector IsExact, IntegerVector Verbose, IntegerVector L, IntegerVector ReturnComputations, IntegerVector InitGiven, NumericVector Init, IntegerVector Sample_Gamma_From_Bank, NumericMatrix Bank, IntegerVector P_k_i_is_given, NumericMatrix P_k_i_precomputed, NumericVector Pki_Integration_Stepsize, IntegerVector Prior_Type, IntegerVector Two_Layer_Dirichlet_I1);
RcppExport SEXP _mcleod_rcpp_Gibbs_Prob_Results_BetaH(SEXP x_vecSEXP, SEXP n_vecSEXP, SEXP a_vecSEXP, SEXP CDF_valueSEXP, SEXP thetaSEXP, SEXP n_gibbsSEXP, SEXP n_gibbs_burninSEXP, SEXP IsExactSEXP, SEXP VerboseSEXP, SEXP LSEXP, SEXP ReturnComputationsSEXP, SEXP InitGivenSEXP, SEXP InitSEXP, SEXP Sample_Gamma_From_BankSEXP, SEXP BankSEXP, SEXP P_k_i_is_givenSEXP, SEXP P_k_i_precomputedSEXP, SEXP Pki_Integration_StepsizeSEXP, SEXP Prior_TypeSEXP, SEXP Two_Layer_Dirichlet_I1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_vec(x_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_vec(n_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_vec(a_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CDF_value(CDF_valueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_gibbs(n_gibbsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_gibbs_burnin(n_gibbs_burninSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type IsExact(IsExactSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Verbose(VerboseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ReturnComputations(ReturnComputationsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type InitGiven(InitGivenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Init(InitSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Sample_Gamma_From_Bank(Sample_Gamma_From_BankSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Bank(BankSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type P_k_i_is_given(P_k_i_is_givenSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type P_k_i_precomputed(P_k_i_precomputedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Pki_Integration_Stepsize(Pki_Integration_StepsizeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Prior_Type(Prior_TypeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Two_Layer_Dirichlet_I1(Two_Layer_Dirichlet_I1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Gibbs_Prob_Results_BetaH(x_vec, n_vec, a_vec, CDF_value, theta, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, ReturnComputations, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Generate_Fast_Gamma_Bank
NumericMatrix rcpp_Generate_Fast_Gamma_Bank(IntegerVector Size);
RcppExport SEXP _mcleod_rcpp_Generate_Fast_Gamma_Bank(SEXP SizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Size(SizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Generate_Fast_Gamma_Bank(Size));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Generate_Gamma_from_Fast_Gamma_Bank
NumericVector rcpp_Generate_Gamma_from_Fast_Gamma_Bank(NumericVector x, NumericMatrix Bank);
RcppExport SEXP _mcleod_rcpp_Generate_Gamma_from_Fast_Gamma_Bank(SEXP xSEXP, SEXP BankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Bank(BankSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Generate_Gamma_from_Fast_Gamma_Bank(x, Bank));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _mcleod_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// integrate_test
Rcpp::List integrate_test();
RcppExport SEXP _mcleod_integrate_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(integrate_test());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mcleod_rcpp_Gibbs_Prob_Results_BetaH", (DL_FUNC) &_mcleod_rcpp_Gibbs_Prob_Results_BetaH, 20},
    {"_mcleod_rcpp_Generate_Fast_Gamma_Bank", (DL_FUNC) &_mcleod_rcpp_Generate_Fast_Gamma_Bank, 1},
    {"_mcleod_rcpp_Generate_Gamma_from_Fast_Gamma_Bank", (DL_FUNC) &_mcleod_rcpp_Generate_Gamma_from_Fast_Gamma_Bank, 2},
    {"_mcleod_rcpp_hello_world", (DL_FUNC) &_mcleod_rcpp_hello_world, 0},
    {"_mcleod_integrate_test", (DL_FUNC) &_mcleod_integrate_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mcleod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
