# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_Gibbs_Prob_Results <- function(x_vec, n_vec, a_vec, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, Prior_Hyper_Parameters_BetaH_L, Prior_Hyper_Parameters_BetaH_U, Prior_Hyper_Parameters_2LDT, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1, covariates_given, covariates, proposal_sd, beta_prior_sd, beta_init, Noise_Type, manual_beta_dist_given, manual_beta_dist_values, manual_beta_dist_Probs, do_P_k_i_hashing, P_k_i_hashing_resolution, offset_vec) {
    .Call(`_mcleod_rcpp_Gibbs_Prob_Results`, x_vec, n_vec, a_vec, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, Prior_Hyper_Parameters_BetaH_L, Prior_Hyper_Parameters_BetaH_U, Prior_Hyper_Parameters_2LDT, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1, covariates_given, covariates, proposal_sd, beta_prior_sd, beta_init, Noise_Type, manual_beta_dist_given, manual_beta_dist_values, manual_beta_dist_Probs, do_P_k_i_hashing, P_k_i_hashing_resolution, offset_vec)
}

rcpp_Generate_Fast_Gamma_Bank <- function(Size) {
    .Call(`_mcleod_rcpp_Generate_Fast_Gamma_Bank`, Size)
}

rcpp_Generate_Gamma_from_Fast_Gamma_Bank <- function(x, Bank) {
    .Call(`_mcleod_rcpp_Generate_Gamma_from_Fast_Gamma_Bank`, x, Bank)
}

rcpp_Gibbs_Prob_Results_Multiple <- function(threadpool_size, x_vec_list, n_vec, a_vec, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, Prior_Hyper_Parameters_BetaH_L, Prior_Hyper_Parameters_BetaH_U, Prior_Hyper_Parameters_2LDT, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed_list, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1, covariates_given, covariates, proposal_sd, beta_prior_sd, beta_init, Noise_Type, manual_beta_dist_given, manual_beta_dist_values, manual_beta_dist_Probs, do_P_k_i_hashing, P_k_i_hashing_resolution, offset_vec) {
    .Call(`_mcleod_rcpp_Gibbs_Prob_Results_Multiple`, threadpool_size, x_vec_list, n_vec, a_vec, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, Prior_Hyper_Parameters_BetaH_L, Prior_Hyper_Parameters_BetaH_U, Prior_Hyper_Parameters_2LDT, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed_list, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1, covariates_given, covariates, proposal_sd, beta_prior_sd, beta_init, Noise_Type, manual_beta_dist_given, manual_beta_dist_values, manual_beta_dist_Probs, do_P_k_i_hashing, P_k_i_hashing_resolution, offset_vec)
}

