# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_Gibbs_Prob_Results_BetaH <- function(x_vec, n_vec, a_vec, CDF_value, theta, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, ReturnComputations, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1) {
    .Call(`_mcleod_rcpp_Gibbs_Prob_Results_BetaH`, x_vec, n_vec, a_vec, CDF_value, theta, n_gibbs, n_gibbs_burnin, IsExact, Verbose, L, ReturnComputations, InitGiven, Init, Sample_Gamma_From_Bank, Bank, P_k_i_is_given, P_k_i_precomputed, Pki_Integration_Stepsize, Prior_Type, Two_Layer_Dirichlet_I1)
}

rcpp_Generate_Fast_Gamma_Bank <- function(Size) {
    .Call(`_mcleod_rcpp_Generate_Fast_Gamma_Bank`, Size)
}

rcpp_Generate_Gamma_from_Fast_Gamma_Bank <- function(x, Bank) {
    .Call(`_mcleod_rcpp_Generate_Gamma_from_Fast_Gamma_Bank`, x, Bank)
}

rcpp_hello_world <- function() {
    .Call(`_mcleod_rcpp_hello_world`)
}

integrate_test <- function() {
    .Call(`_mcleod_integrate_test`)
}

